### ISSUE TITLE
Unable to use addon after installation

### ISSUE THREAD

**Issue by vitor-ao** [wanze/statamic-super-static-cache#2]
After installation, when opening the Addons page, it returns the following error:
```
[2018-12-12 11:15:42] dev.ERROR: ErrorException: Invalid argument supplied for foreach() in K:\xampp\htdocs\site\addons\SuperStaticCache\CacheExclusionChecker.php:124
```

**Comment by wanze** [comment]
@vitor-ao Thanks for testing. Do you have any whitelisted query strings configured? If so, could you post the YAML here? If not, could you try the following:

* Open `site/addons/SuperStaticCache/default.yaml`
* Change the line for the whitlisted query strings to: `whitelisted_query_strings: []`

**Comment by vitor-ao** [comment]
No, I don't have any whitelisted query strings yet. Adding the brackets solved the problem.
