### ISSUE TITLE
Disable cache cookie not being set

### ISSUE THREAD

**Issue by justinhough** [wanze/statamic-super-static-cache#3]
I am unable to get the cookie to disable cache to show within DevTools while being logged in.

I have it set as the default cookie name `statamic_static_cache_skip` and have the full measure settings in place, but still the anonymous cache seems to be overriding the authenticated user.

## Cache Settings
```
stache_always_update: false
cache_tags_enabled: true
static_caching_enabled: true
static_caching_type: file
static_caching_file_path: static
static_caching_ignore_query_strings: false
static_caching_lock_hold_length: 0
stache_lock_enabled: true
stache_lock_wait_length: 30
```

## Super Cache Settings
```
cache_disabled_authenticated: true
cache_disabled_cookie_name: statamic_static_cache_skip
```

## HTACCESS 
```
RewriteCond %{DOCUMENT_ROOT}/static/%{REQUEST_URI}_%{QUERY_STRING}\.html -s
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{HTTP_COOKIE} !^.*statamic_static_cache_skip.*$
RewriteRule .* static/%{REQUEST_URI}_%{QUERY_STRING}\.html [L,T=text/html]
```

**Comment by wanze** [comment]
Hi @justinhough 

I just checked on two sites and it seems to work fine: When I log into Statamic, the `statamic_static_cache_skip` cookie is set. And it gets deleted when logging out. 

What version of Statamic and the module are you using?

Some things to check:
* Can you confirm (via dev tools) that the cookie is not present after a login?
* Your settings look fine, but are there any chances that you overwrite some settings by environment, e.g. that the cache is only disabled for certain user roles?

If you are able to debug, check if the addon's listener is catching the `auth.login` event. If so, follow the logic to check why the cookie is not set. The relevant line for the breakpoint is here: https://github.com/wanze/statamic-super-static-cache/blob/master/SuperStaticCacheListener.php#L32

Hope that helps.

Cheers

**Comment by justinhough** [comment]
Hi @wanze 

I am using Statamic `2.11.10` and the plugin is `1.1.1`.

This is my env file:
```
APP_ENV=dev
APP_URL=https://domain.local/
SESSION_DRIVER=cookie
```

I was able to clear the application cache and now the cookie is being set properly once I log in, but it appears that even with the cookie set the authenticated user is only seeing cached content. Now that the cookie is being set I am at a loss as to why the cache content is not avoided with the same implementation as above.

To give you an idea of what I have been trying to test. I am trying to have content for authenticated users that doesn't get rendered if you're unauthenticated. From what I noticed the content shows if you start with the logged in user (cache cleared), but once an unauthenticated user visits the site the cache gets set for that page and the content for authenticated users will no longer show but pull directly from cache.

Is there anything more that I should attempt with the `.htaccess` file to have it avoid the static cache?

**Comment by justinhough** [comment]
@wanze I was doing a little more debugging on this and found that the issue I am having only exists when using Valet locally, so I am assuming that it might have something to do with Nginx.

I deployed the updated caching settings to a testing server that uses Apache / .htaccess and was able to see the authenticated user passed properly with pages not cached.

I will try to do some more debugging on the local Valet environment to see if I can figure out a good way to have this working locally with Nginx which I am assuming might be the main issue.

**Comment by wanze** [comment]
Hi @justinhough,

Glad you found the issue. In order to support Nginx, we need to adjust the rewrite rules to skip the redirect if the cookie is being set, similar to the additional rewrite rule in `.htaccess`. If you find out how to make this work with Nginx, please let me know or send a pull request :)

Cheers
